name: Manometer Reader
version: "0.1.0"
slug: manometer_reader
description: Reads an analog gauge from RTSP and publishes the value via MQTT
# url: "https://github.com/CrazyHAEBDF/ha-addons/tree/main/manometer_reader"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto

options:
  rtsp_url: ""
  interval_sec: 10
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_topic: "home/manometer/pressure"
  roi: [0, 0, 0, 0]
  center: [0, 0]
  angle_min_deg: 225
  angle_max_deg: 315
  value_min: 0.0
  value_max: 3.0

schema:
  rtsp_url: str
  interval_sec: int(1,3600)
  mqtt_host: str
  mqtt_port: int(1,65535)
  mqtt_topic: str
  roi:
    - int
    - int
    - int
    - int
  center:
    - int
    - int
  angle_min_deg: float
  angle_max_deg: float
  value_min: float
  value_max: float
